class Solution:
    '''
    [Easy Problem]

        You are given two strings "s" and "t".

        String "t" is generated by random shuffling string "s" and then add one more letter 
        at a random position.

        Return the letter that was added to "t".
    
    
    '''

    def findTheDifference(self, s: str, t: str) -> str:
        freak = {}
        for char in s:
            freak[char] = freak.get(char, 0) + 1
        for char in t:
            if freak.get(char, 0):
                freak[char] -= 1
            else: return char



if __name__ == "__main__":
    print(f"Want : {"e"}, Was : {Solution().findTheDifference(s = "abcd", t = "abcde")}")
    print(f"Want : {"y"}, Was : {Solution().findTheDifference(s = "", t = "y")}")